### ISSUE TITLE
if i work 12 hours per day?? See the example

### ISSUE THREAD

**Issue by dobbbri** [csakaszamok/csak-ext-timer#1]
I work 12 hours a day, every 2 days I would have worked 1 more day, but the day only changes after 24 hours:
ex:

day 1 = 12 hours
day 2 = 12 hours
total = 24 hours / 8 => 3 days worked

but it's scoring 2 days

**Comment by csakaszamok** [comment]
What do you want to see?
a) (24h/day): 1 day + 7 hours
b) (12h/day): 2 day + 7 hours
c) (8h/day): 4 day + 7 hours
d) Only hours: 31 hours

In the new version (0.5.5) you can set whatever you want:
Set in the config this value:
a) 24
b) 12
c) 8
d) 0

**Comment by dobbbri** [comment]
tanks!!!! 👍
